### PR TITLE
Made some changes to Schema and added job routes

### LINKED ISSUE #39: add job routes

### PR DESCRIPTION
**Pull request by 201901407**

### CODE REVIEW

**Comment by 201901407** [comment]
Issue #27

**Review by MananDesai54 — CHANGES_REQUESTED** [review]
Prefer async await over promises and inside create job use middleware for user Authorization

**Review by MananDesai54 — APPROVED** [review]

**Review by MananDesai54 — APPROVED** [review]
Done

**Review by MananDesai54 — APPROVED** [review]
Jobs routes done

**Comment by dkp1903** [comment]
give @201901407 75 points

**Comment by dkp1903** [comment]
give @MananDesai54 25 points

**Pull request merged**
